# Generated by Django 5.0.7 on 2024-10-26 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_analyzer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='text',
            name='sentiment_score',
        ),
        migrations.AddField(
            model_name='text',
            name='sentiment_textblob',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='text',
            name='sentiment_transformer',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='text',
            name='sentiment_vader',
            field=models.FloatField(default=0.0),
        ),
    ]
